-- Team Data Migration: JSON to Neon Database
-- Generated on: 2025-07-01T01:37:48.295Z
-- Total records: 23

-- Clear existing data (uncomment if needed)
-- DELETE FROM team_members;

-- Insert team members
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('chandrabhan-patel', 'Chandrabhan Patel', 'Technical Secretary', 'technical.secretary@iitgn.ac.in', 'CP', 'from-blue-600', 'to-purple-600', 'leadership', '/team/chandrabhan-patel-1748809788749.jpg', true, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('anmol-kumar', 'Anmol Kumar', 'Technical Coordinator', 'kumaranmol@iitgn.ac.in', 'AK', 'from-purple-600', 'to-pink-600', 'coordinator', '/team/Anmol-Kumar.jpg', false, true, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('naveen-pal', 'Naveen Pal', 'Management Coordinator', '23110216@iitgn.ac.in', 'NP', 'from-green-600', 'to-teal-600', 'coordinator', '/team/Naveen-Pal.jpg', false, true, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('ridham-patel', 'Ridham Patel', 'Management Coordinator', '23110238@iitgn.ac.in', 'RP', 'from-emerald-600', 'to-cyan-600', 'coordinator', '/team/ridham-patel.jpg', false, true, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('kalp-shah', 'Kalp Shah', 'Outreach Coordinator', '24110152@iitgn.ac.in', 'KS', 'from-indigo-600', 'to-purple-600', 'coordinator', '/team/Kalp-Shah.jpg', false, true, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('mukul-meena', 'Mukul Meena', 'Website/Social Media/Design Lead', 'mukul.meena@iitgn.ac.in', 'MM', 'from-orange-600', 'to-red-600', 'coordinator', '/team/mukul-meena-1748385087882.jpg', false, true, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('arpan-gupta', 'Arpan Gupta', 'General Member', '24110051@iitgn.ac.in', 'AG', 'from-blue-600', 'to-indigo-600', 'general', '/team/Arpan-Gupta.jpeg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('rachit-mehta', 'Rachit Mehta', 'General Member', '23110261@iitgn.ac.in', 'RM', 'from-purple-600', 'to-pink-600', 'general', '/team/Rachit-Mehta.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('chaitanya-bhoite', 'Chaitanya Yogesh Bhoite', 'General Member', '24110086@iitgn.ac.in', 'CB', 'from-green-600', 'to-teal-600', 'general', NULL, false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('raj-modi', 'Raj Modi', 'General Member', '24110282@iitgn.ac.in', 'RM', 'from-orange-600', 'to-red-600', 'general', '/team/raj-modi.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('siddhesh-umarjee', 'Siddhesh Umarjee', 'General Member', '23110347@iitgn.ac.in', 'SU', 'from-cyan-600', 'to-blue-600', 'general', '/team/Siddhesh-Umarjee.JPG', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('beli', 'Beli', 'General Member', '24110066@iitgn.ac.in', 'B', 'from-emerald-600', 'to-green-600', 'general', '/team/Beli-Dedhia.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('jash-pasad', 'Jash Pasad', 'General Member', '24110146@iitgn.ac.in', 'JP', 'from-violet-600', 'to-purple-600', 'general', '/team/JASH-PASAD.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('akul-gupta', 'Akul Gupta', 'General Member', '24110027@iitgn.ac.in', 'AG', 'from-rose-600', 'to-pink-600', 'general', '/team/Akul-Gupta.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('indrayudh-mandal', 'Indrayudh Mandal', 'General Member', '24210041@iitgn.ac.in', 'IM', 'from-amber-600', 'to-orange-600', 'general', '/team/Indrayudh-Mandal.jpeg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('piyush-makhijani', 'Piyush Makhijani', 'General Member', '24110259@iitgn.ac.in', 'PM', 'from-lime-600', 'to-green-600', 'general', '/team/Piyush-Makhijani.png', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('satvik-kadian', 'Satvik Kadian', 'General Member', '24110317@iitgn.ac.in', 'SK', 'from-sky-600', 'to-cyan-600', 'general', '/team/Satvik-Kadian.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('romit-mohane', 'Romit Mohane', 'General Member', '23110279@iitgn.ac.in', 'RM', 'from-fuchsia-600', 'to-purple-600', 'general', '/team/Romit-Mohane.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('akshit-chhabra', 'Akshit Chhabra', 'General Member', '24110026@iitgn.ac.in', 'AC', 'from-teal-600', 'to-cyan-600', 'general', '/team/AkshitChhabra.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('vishal-boliwal', 'Vishal Boliwal', 'Design Team', '24110080@iitgn.ac.in', 'VB', 'from-pink-600', 'to-rose-600', 'design', '/team/Vishal-boliwal.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('dhru-harsh', 'Dhru Harsh Darshakbhai', 'Design Team', '24110107@iitgn.ac.in', 'DD', 'from-indigo-600', 'to-blue-600', 'design', '/team/Harsh-Dhru.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('srushti-dandekar', 'Srushti Dandekar', 'Social Media Team', '23110084@iitgn.ac.in', 'SD', 'from-purple-600', 'to-violet-600', 'social', '/team/Srushti-Dandekar.jpg', false, false, NOW(), NOW());
INSERT INTO team_members (id, name, position, email, initials, gradient_from, gradient_to, category, photo_path, is_secretary, is_coordinator, created_at, updated_at) VALUES ('harshal-rana', 'Harshal Kundanlal Rana', 'Social Media Team', '24110131@iitgn.ac.in', 'HR', 'from-emerald-600', 'to-teal-600', 'social', NULL, false, false, NOW(), NOW());

-- Verify migration
SELECT COUNT(*) as total_members FROM team_members;
SELECT category, COUNT(*) as count FROM team_members GROUP BY category;
